version: "3"
services:
  corenlp:
    image: 'sld3/corenlp:3.6.0'
    ports:
      - '9000:9000'
    restart: 'always'
    deploy:
      resources:
        limits:
          memory: 1024M

  opennmt:
    image: 'sld3/opennmt:latest'
    volumes:
      - './question_generation/data/:/root/data'
    command: >
      bash -c "cd /root/opennmt && th tools/translation_server.lua -host 0.0.0.0
      -port 5556  -model /root/data/model.t7 -beam_size 12 -replace_unk true"
    depends_on:
      - corenlp
    ports:
      - '5556:5556'
    restart: 'always'
    deploy:
      resources:
        limits:
          memory: 512M

  opennmtchitchat:
    image: 'sld3/opennmt:611e636_distro5beb83'
    volumes:
      - './opennmt_chitchat/data/:/root/data'
    command: >
      bash -c "cd /root/opennmt && th tools/translation_server.lua -host 0.0.0.0
      -port 5556  -model /root/data/CPU_epoch5_14.62.t7
      -beam_size 12 -replace_unk false"
    ports:
      - '5557:5556'
    restart: 'always'

  opennmtfbpost:
    image: 'sld3/opennmt:611e636_distro5beb83'
    volumes:
      - './fbnews_chitchat/data/:/root/data'
    command: >
      bash -c "cd /root/opennmt && th tools/translation_server.lua -host 0.0.0.0
      -port 5556  -model /root/data/model_epoch18_93.23_release.t7
      -beam_size 12 -replace_unk false"
    ports:
      - '5559:5556'
    restart: 'always'

  bidaf:
    image: 'sld3/bi-att-flow:0.1.0'
    ports:
      - '1995:1995'
    restart: 'always'
    deploy:
      resources:
        limits:
          memory: 512M
  alice:
    image: 'sld3/alice_chat:0.1.0'
    volumes:
      - './ALICEChatAPI:/src'
    command: python -u server.py
    restart: 'always'
    deploy:
      resources:
        limits:
          memory: 512M
