version: "3"
services:
  corenlp:
    image: 'sld3/corenlp:3.6.0'
    ports:
      - '9000:9000'
    deploy:
      resources:
        limits:
          memory: 1024M

  opennmt:
    image: 'sld3/opennmt:latest'
    volumes:
      - './question_generation/data/:/root/data'
    command: bash -c "cd /root/opennmt && th tools/translation_server.lua -host 0.0.0.0 -port 5556  -model /root/data/model.t7  -beam_size 12"
    depends_on:
      - corenlp
    ports:
      - '5556:5556'
    deploy:
      resources:
        limits:
          memory: 512M

  bidaf:
    image: 'sld3/bi-att-flow:0.1.0'
    ports:
      - '1995:1995'
    deploy:
      resources:
        limits:
          memory: 512M

  tf_chatbot:
    build:
      context: './tf_chatbot_seq2seq_antilm/'
    image: 'tf_chatbot:0.1.0'
    ports:
      - '5000:5000'
    volumes:
      - ./tf_chatbot_seq2seq_antilm:/src
    deploy:
      resources:
        limits:
          memory: 2048M

  dialog_tracker:
    build:
      context: './dialog_tracker/'
    image: 'dialog_tracker:1'
    volumes:
      - ./dialog_tracker:/src
    depends_on:
      - corenlp
      - opennmt
      - tf_chatbot
    deploy:
      resources:
        limits:
          memory: 512M

