version: "3"
services:
  corenlp:
    image: 'sld3/corenlp:3.6.0'
    restart: 'no'
    ports:
      - '9000:9000'

  opennmt:
    image: 'sld3/opennmt:latest'
    restart: 'no'
    volumes:
      - './question_generation/data/:/root/data'
    command: bash -c "cd /root/opennmt && th tools/translation_server.lua -host 0.0.0.0 -port 5556  -model /root/data/model.t7  -beam_size 12"
    depends_on:
      - corenlp
    ports:
      - '5556:5556'

  bidaf:
    image: 'sld3/bi-att-flow:0.1.0'
    restart: 'no'
    ports:
      - '1995:1995'

  dialog_tracker:
    build:
      context: './dialog_tracker/'
    image: 'dialog_tracker:1'
    volumes:
      - ./dialog_tracker:/src
    depends_on:
      - corenlp
      - opennmt

