version: "3"
services:
  dialog_tracker_json_api:
    build:
      context: './dialog_tracker/'
    image: 'dialog_tracker:1'
    command: python main_api.py
    restart: 'no'
    volumes:
      - ./dialog_tracker:/src
    depends_on:
      - corenlp
      - opennmt
      - opennmtchitchat
      - opennmtfbpost
    ports:
      - '5000:5000'
    deploy:
      resources:
        limits:
          memory: 512M

