version: "3"
services:
  dialog_tracker:
    build:
      context: './dialog_tracker/'
    image: 'dialog_tracker:1'
    command: python -u telegram_main.py test2
    restart: 'always'
    volumes:
      - ./dialog_tracker:/src
    depends_on:
      - corenlp
      - opennmt
      - opennmtchitchat
      - opennmtfbpost
      - opennmtsummary
      - bigartm
    deploy:
      resources:
        limits:
          memory: 512M

